### ISSUE TITLE
(facette 3 UI) feature request: prefix resolution for p o list

### ISSUE THREAD

**Issue by seebi** [Scaseco/facete3#5]
instead or URIs I would like to see prefixed qnames. This will allow for more space for literals :)

btw: great project :-)

**Comment by Aklakan** [comment]
Semi-done; short labels are now used everywhere - possibly based on resource's local names.
However, using a source for prefixes, such as http://prefix.cc would be a worthy addition.

**Comment by Aklakan** [comment]
Pressing the 's' key now context-sensitively shows the sparql query powering the data of the active component (facet/facet value/matches list) - these queries are normalized to by default use prefix declarations from a prefix.cc snapshot on the classpath.

**Comment by seebi** [comment]
great - Where can I download the latest build?

**Comment by Aklakan** [comment]
The latest snapshot is now available as a release bundle: https://github.com/hobbit-project/facete3/releases :)

**Comment by Aklakan** [comment]
So I think in order to close this issue, I should add toggles to switch the display of IRIs using (1) labels - this is what is done right now (2) compact URIs - in progress. A probably not very useful option (3) would be full IRI display - but maybe this is not useful as spacebar always shows the full IRI of the focused item.

**Comment by seebi** [comment]
> The latest snapshot is now available as a release bundle: https://github.com/hobbit-project/facete3/releases :)

Just tested and got an error like this:

```
facete3
Exception in thread "main" java.lang.NullPointerException
	at org.aksw.facete3.cli.main.MainCliFacete3.main(MainCliFacete3.java:1017)
```
is there a new trick?

**Comment by Aklakan** [comment]
Oops - never tested it without arguments because there is not much use for that

Invocation with `-h` and `--help` should display some options - and more documentation is here: https://github.com/hobbit-project/facete3/tree/develop/facete3-core-parent/facete3-cli

**Comment by seebi** [comment]
This is partially incorrect since -h reveals this error:

```
∴ facete3 -h
Exception in thread "main" org.apache.jena.riot.RiotNotFoundException: Not found: -h
	at org.apache.jena.riot.RDFParser.openTypedInputStream(RDFParser.java:394)
	at org.apache.jena.riot.RDFParser.parseURI(RDFParser.java:301)
	at org.apache.jena.riot.RDFParser.parse(RDFParser.java:295)
	at org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:506)
	at org.apache.jena.riot.RDFDataMgr.parseFromURI(RDFDataMgr.java:890)
	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:221)
	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:102)
	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:93)
	at org.apache.jena.riot.RDFDataMgr.loadModel(RDFDataMgr.java:335)
	at org.aksw.facete3.cli.main.MainCliFacete3.main(MainCliFacete3.java:1037)
```

**Comment by seebi** [comment]
> So I think in order to close this issue, I should add toggles to switch the display of IRIs using (1) labels - this is what is done right now (2) compact URIs - in progress. A probably not very useful option (3) would be full IRI display - but maybe this is not useful as spacebar always shows the full IRI of the focused item.

for me, the current local name presentation is fine (yes, prefix usage is great but not a MUST).

I found an issue with the current local name calculation:

The resource https://timetracker.eccenca.com/records/1525383613220
is currently presented as "records"
but should be presented as "1525383613220"

**Comment by Aklakan** [comment]
Right, so I should use a different namespace/localname split method.
At present, the code uses `Util.splitNamespaceXML`. However, as numbers are not valid starts of an XML namespace, in the case of '/123abc' the split only happens after '/123' - and in this case, if there are only numbers, apparently it happens on the preceding slash.

**Comment by Aklakan** [comment]
The latest branch now features hitting the 'l' key to toggle between full RDF terms and labels; which is very useful when labels are derived in suboptimal ways.

**Comment by Aklakan** [comment]
Prefix display toggle is now implemented using the 'p' key;
the CLI supports specification of custom prefixes via the -p rdfResource option.

Improvement of the CLI is subject of #31
